presubmits:
  https://gke-internal-review.googlesource.com/cloud-run-dmc/serving:
  - name: pull-build-unit-presubmit
    always_run: true
    decorate: true
    path_alias: github.com/knative/serving
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
        command:
        - ./test/presubmit-tests.sh
        args:
        - --build-tests
        - --unit-tests
