periodics:
 - cron: '1 17 * * 0' # Run at 10:01PST (17:01 UTC) on sunday
   name: ci-kubernetes-e2e-gke-scale-correctness
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - args:
       - --timeout=660
       - --bare
       - --scenario=kubernetes_e2e
       - --upload=gs://gob-prow/logs
       - --
       - --check-leaked-resources
       - --cluster=gke-scale-cluster
       - --deployment=gke
       - --extract=gke-latest
       - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
       - --gcp-node-image=gci
       - --gcp-project=k8s-scale-testing
       - --gcp-zone=us-east1-a
       - --ginkgo-parallel=30
       - --gke-command-group=beta
       - --gke-create-command=container clusters create --quiet --enable-ip-alias --create-subnetwork name=ip-alias-subnet --cluster-ipv4-cidr=/11 --services-ipv4-cidr=/18
       - --gke-environment=staging
       - --gke-shape={"default":{"Nodes":4999,"MachineType":"g1-small"},"heapster-pool":{"Nodes":1,"MachineType":"n1-standard-16"}}
       - --provider=gke
       - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[DisabledForLargeClusters\] --allowed-not-ready-nodes=40 --node-schedulable-timeout=90m --minStartupPods=8
       - --timeout=630m
       image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
       resources:
         requests:
           memory: "6Gi"
 - cron: '1 17 * * 6' # Run at 10:01PST (17:01 UTC) on saturday
   name: ci-kubernetes-e2e-gke-large-correctness
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - args:
       - --timeout=480
       - --bare
       - --scenario=kubernetes_e2e
       - --upload=gs://gob-prow/logs
       - --
       - --check-leaked-resources
       - --cluster=gke-scale-cluster
       - --deployment=gke
       - --extract=gke-latest
       - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
       - --gcp-node-image=gci
       - --gcp-project=k8s-scale-testing
       - --gcp-zone=us-east1-a
       - --ginkgo-parallel=30
       - --gke-command-group=beta
       - --gke-create-command=container clusters create --quiet --enable-ip-alias --create-subnetwork name=ip-alias-subnet --cluster-ipv4-cidr=/12 --services-ipv4-cidr=/19
       - --gke-environment=staging
       - --gke-shape={"default":{"Nodes":2000,"MachineType":"g1-small"},"heapster-pool":{"Nodes":1,"MachineType":"n1-standard-8"}}
       - --provider=gke
       - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[DisabledForLargeClusters\] --minStartupPods=8
       - --timeout=450m
       image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
       resources:
         requests:
           memory: "6Gi"

 - cron: '1 3 * * 0' # Run at 20:01PST on saturday (03:01 UTC) on sunday
   name: ci-kubernetes-e2e-gke-small-correctness-canary
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - args:
       - --timeout=220
       - --bare
       - --scenario=kubernetes_e2e
       - --upload=gs://gob-prow/logs
       - --
       - --check-leaked-resources
       - --cluster=gke-scale-cluster-canary
       - --deployment=gke
       - --extract=gke-latest
       - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
       - --gcp-node-image=gci
       - --gcp-project=k8s-scale-testing
       - --gcp-zone=us-east1-a
       - --ginkgo-parallel=30
       - --gke-command-group=beta
       - --gke-create-command=container clusters create --quiet --enable-ip-alias --create-subnetwork name=ip-alias-subnet --cluster-ipv4-cidr=/16 --services-ipv4-cidr=/19
       - --gke-environment=prod
       - --gke-shape={"default":{"Nodes":200,"MachineType":"g1-small"},"heapster-pool":{"Nodes":1,"MachineType":"n1-standard-8"}}
       - --provider=gke
       - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[DisabledForLargeClusters\] --minStartupPods=8
       - --timeout=200m
       image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
