periodics:
 - interval: 4h
   name: periodic-syllogi-cli-e2e-dhcp-gcr-onprem
   labels:
     preset-service-account: "true"
     preset-syllogi-setup: "true"
   decorate: true
   extra_refs:
   - org: gke-internal.googlesource.com/syllogi
     repo: cluster-management
     base_ref: master
     path_alias: gke-internal.googlesource.com/syllogi/cluster-management
     clone_uri: https://gke-internal.googlesource.com/syllogi/cluster-management
   decoration_config:
     gcs_configuration:
       bucket: "syllogi-gob-prow"
       path_strategy: "explicit"
   spec:
     containers:
     - image: gcr.io/syllogi-ci/syllogi-testing:experimental
       imagePullPolicy: Always
       command:
       - gkectl/scripts/ci-dhcp-gcr.sh

 - interval: 4h
   name: periodic-syllogi-cli-e2e-ipam-privatereg-onprem
   labels:
     preset-service-account: "true"
     preset-syllogi-setup: "true"
   decorate: true
   extra_refs:
   - org: gke-internal.googlesource.com/syllogi
     repo: cluster-management
     base_ref: master
     path_alias: gke-internal.googlesource.com/syllogi/cluster-management
     clone_uri: https://gke-internal.googlesource.com/syllogi/cluster-management
   decoration_config:
     gcs_configuration:
       bucket: "syllogi-gob-prow"
       path_strategy: "explicit"
   spec:
     containers:
     - image: gcr.io/syllogi-ci/syllogi-testing:experimental
       imagePullPolicy: Always
       command:
       - gkectl/scripts/ci-ipam-privatereg.sh
