prowjob_namespace: default
pod_namespace: test-pods
log_level: info

periodics:
- interval: 10m
  agent: kubernetes
  name: gob-checkout-test
  spec:
    containers:
    - env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      image: gcr.io/k8s-testimages/gob-test:v20180125-832d1e9
      volumeMounts:
      - mountPath: /etc/service-account
        name: service
        readOnly: true
    volumes:
    - name: service
      secret:
        secretName: service-account
