plank:
  job_url_template: 'https://gubernator-internal.googleplex.com/build/gke-prow/{{if eq .Spec.Type "presubmit"}}pr-logs/pull{{else if eq .Spec.Type "batch"}}pr-logs/pull{{else}}logs{{end}}{{if ne .Spec.Refs.Org ""}}{{if ne .Spec.Refs.Org "kubernetes"}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}{{else if ne .Spec.Refs.Repo "kubernetes"}}/{{.Spec.Refs.Repo}}{{end}}{{end}}{{if eq .Spec.Type "presubmit"}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}{{else if eq .Spec.Type "batch"}}/batch{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}/'

prowjob_namespace: default
pod_namespace: test-pods
log_level: info

presets:
- labels:
    preset-service-account: true
  env:
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /etc/service-account/service-account.json
  volumes:
  - name: service
    secret:
      secretName: service-account
  volumeMounts:
  - name: service
    mountPath: /etc/service-account
    readOnly: true
# storage / caching presets
- labels:
    preset-bazel-scratch-dir: true
  env:
  - name: TEST_TMPDIR
    value: /bazel-scratch/.cache/bazel
  volumes:
  - name: bazel-scratch
    emptyDir: {}
  volumeMounts:
  - name: bazel-scratch
    mountPath: /bazel-scratch/.cache

presubmits:
  elafros/elafros:
  - name: pull-elafros-bazel-test
    agent: kubernetes
    context: pull-elafros-bazel-test
    always_run: true
    rerun_command: "/test pull-elafros-bazel-test"
    trigger: "(?m)^/test( all| pull-elafros-bazel-test),?(\\s+|$)"
    labels:
      preset-service-account: true
      preset-bazel-scratch-dir: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180228-dabde9ed5-master
        args:
        - "--ssh=/etc/ssh-elafros/ssh-elafros"
        - "--scenario=kubernetes_execute_bazel"
        - "--clean"
        - "--job=$(JOB_NAME)"
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://gke-prow/pr-logs"
        - "--" # end bootstrap args, scenario args below
        - "bazel"
        - "test"
        - '"--workspace_status_command="'
        - "//pkg/..."
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
        volumeMounts:
        - mountPath: /etc/ssh-elafros
          name: ssh-elafros
      volumes:
      - name: ssh-elafros
        secret:
          defaultMode: 256
          secretName: ssh-elafros


periodics:
- interval: 1h
  name: ci-kubernetes-bazel-test
  agent: kubernetes
  labels:
    preset-service-account: true
    preset-bazel-scratch-dir: true
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bazelbuild:v20180201-0184a54dc-0.10.0
      args:
      - --clean
      - --job=$(JOB_NAME)
      - --repo=gke-internal.googlesource.com/kubernetes
      - --service-account=/etc/service-account/service-account.json
      - --upload=gs://gke-prow/logs
      - --scenario=kubernetes_bazel
      - -- # end bootstrap args, scenario args below
      - --test=//... -//build/... -//vendor/...
      - --manual-test=//hack:verify-all
      - --test-args=--config=unit
      - --test-args=--build_tag_filters=-e2e,-integration
      - --test-args=--test_tag_filters=-e2e,-integration
      - --test-args=--flaky_test_attempts=3
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "6Gi"
- interval: 30m
  name: ci-kubernetes-build
  agent: kubernetes
  labels:
    preset-service-account: true
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20180215-b2a89850e
      args:
      - --clean
      - --repo=gke-internal.googlesource.com/kubernetes
      - --repo=k8s.io/release
      - --root=/go/src
      - --timeout=30
      - --scenario=kubernetes_build
      - --upload=gs://gke-prow/logs
      - --
      - --fast
      - --release=kubernetes-release-gke-internal
      - --push-build-script=../../k8s.io/release/push-build.sh
      env:
      - name: DOCKER_IN_DOCKER_ENABLED
        value: true
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 3
          memory: "8Gi"
      volumeMounts:
      - name: docker-graph
        mountPath: /docker-graph
    volumes:
    - name: docker-graph
      emptyDir: {}
- interval: 1h
  name: ci-kubernetes-integration
  agent: kubernetes
  labels:
    preset-service-account: true
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bootstrap:v20180215-b2a89850e
      args:
      - --clean
      - --repo=gke-internal.googlesource.com/kubernetes
      - --timeout=100
      - --scenario=kubernetes_verify
      - --upload=gs://gke-prow/logs
      - --
      - --branch=master
      - --force
      - --prow
      env:
      - name: DOCKER_IN_DOCKER_ENABLED
        value: true
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 3
      volumeMounts:
      - name: docker-graph
        mountPath: /docker-graph
    volumes:
    - name: docker-graph
      emptyDir: {}
