presubmits:
  https://cnrm-review.googlesource.com/cnrm:
  - name: cnrm-build
    always_run: true
    decorate: true
    path_alias: cnrm.googlesource.com/cnrm
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-1.11
        command:
        - ./scripts/ci-build.sh
  - name: cnrm-test
    always_run: true
    decorate: true
    path_alias: cnrm.googlesource.com/cnrm
    spec:
      volumes:
      - name: gcp-service-account
        secret:
          secretName: cnrm-eap-prow
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
        command:
        - ./scripts/ci-test.sh
        volumeMounts:
        - name: gcp-service-account
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/service-account.json
        resources:
          requests:
            cpu: 4
            memory: "8Gi"

periodics:
 - interval: 1h
   name: periodic-cnrm-build
   labels:
     preset-service-account: "true"
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-1.11
       args:
       - --clean
       - --repo=cnrm.googlesource.com/cnrm
       - --root=/go/src
       - --upload=gs://gob-prow/logs
       - --scenario=execute
       - --
       - /go/src/cnrm.googlesource.com/cnrm/scripts/ci-build.sh

 - interval: 1h
   name: periodic-cnrm-test
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
       args:
       - --clean
       - --repo=cnrm.googlesource.com/cnrm
       - --root=/go/src
       - --upload=gs://gob-prow/logs
       - --scenario=execute
       - --
       - /go/src/cnrm.googlesource.com/cnrm/scripts/ci-test.sh
       resources:
         requests:
           cpu: 4
           memory: "8Gi"

 - cron: "0,30 * * * *"
   name: periodic-cnrm-release
   decorate: true
   labels:
     preset-dind-enabled: "true"
   extra_refs:
   - org: cnrm.googlesource.com
     repo: cnrm
     base_ref: master
     path_alias: cnrm.googlesource.com/cnrm
     clone_uri: https://cnrm.googlesource.com/cnrm
   spec:
     volumes:
     - name: gcp-service-account
       secret:
         secretName: cnrm-eap-prow
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
       command:
       - runner.sh
       args:
       - ./scripts/release.sh
       volumeMounts:
       - name: gcp-service-account
         mountPath: /var/secrets/google
       env:
       - name: GOOGLE_APPLICATION_CREDENTIALS
         value: /var/secrets/google/service-account.json
       securityContext:
         privileged: true
