presubmits:
  https://cloudesf-review.googlesource.com/gcpproxy:
  - name: gcpproxy-build
    always_run: true
    decorate: true
    path_alias: cloudesf.googlesource.com/gcpproxy
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
        command:
        - ./prow/gcpproxy-build.sh
  - name: cloudesf-presubmit
    always_run: true
    decorate: true
    path_alias: cloudesf.googlesource.com/gcpproxy
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
        command:
        - ./prow/gcpproxy-presubmit.sh
