presubmits:
  https://cloudesf-review.googlesource.com/gcpproxy:
  - name: gcpproxy-build
    always_run: true
    decorate: true
    path_alias: cloudesf.googlesource.com/gcpproxy
    spec:
      containers:
      - image: gcr.io/cloudesf-testing/gcpproxy-prow:v20181031-f39afb6-master
        command:
        - ./prow/gcpproxy-build.sh
  - name: cloudesf-presubmit
    always_run: true
    decorate: true
    path_alias: cloudesf.googlesource.com/gcpproxy
    spec:
      containers:
      - image: gcr.io/cloudesf-testing/gcpproxy-prow:v20181031-f39afb6-master
        command:
        - ./prow/gcpproxy-presubmit.sh
