presubmits:
  https://gke-internal-review.googlesource.com/GoogleCloudPlatform/cronanything:
  - name: cronanything-test
    always_run: true
    decorate: true
    path_alias: k8s.io/cronanything
    labels:
      prow.k8s.io/gerrit-report-label: "Verified"
    spec:
      containers:
      - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
        command:
        - ./hack/test-prow.sh
  - name: cronanything-e2e
    always_run: true
    decorate: true
    path_alias: k8s.io/cronanything
    labels:
      preset-k8s-ssh: "true"
      preset-service-account: "true"
      preset-dind-enabled: "true"
      prow.k8s.io/gerrit-report-label: "Verified"
    extra_refs:
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - command:
        - runner.sh
        - ../../k8s.io/test-infra/scenarios/kubernetes_e2e.py
        args:
        - --check-leaked-resources
        - --cluster=gke-cronanything-cluster
        - --deployment=gke
        - --extract=gke-latest
        - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
        - --gcp-node-image=gci
        - --gcp-zone=us-central1-f
        - --gke-environment=test
        - --gke-shape={"default":{"Nodes":2,"MachineType":"n1-standard-2"}}
        - --provider=gke
        - --test=false
        - --test-cmd=../hack/e2e-prow.sh
        - --timeout=1h
        image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
        securityContext:
          privileged: true
