periodics:
- decorate: true
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-latest-device-plugin-gpu
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --deployment=gke
      - --env=NVIDIA_DRIVER_INSTALLER_DAEMONSET=https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/stable/nvidia-driver-installer/cos/daemonset-preloaded.yaml
      - --extract=gke-latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=80m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master

- decorate: true
  interval: 12h #expensive test
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-latest-device-plugin-gpu-v100
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --deployment=gke
      - --env=NVIDIA_DRIVER_INSTALLER_DAEMONSET=https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/stable/nvidia-driver-installer/cos/daemonset-preloaded.yaml
      - --extract=gke-latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project=k8s-gke-gpu-boskos-v100
      - --gcp-zone=us-central1-f
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-v100,count=2
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=80m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master
