periodics:
- decorate: true
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gci-gke-prod
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-b
      - --gke-environment=prod
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Slow\]|\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=600m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master

- decorate: true
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gci-gke-prod-parallel
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-b
      - --ginkgo-parallel
      - --gke-environment=prod
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=80m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master

- decorate: true
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gci-gke-prod-smoke
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-east1-d
      - --ginkgo-parallel
      - --gke-environment=prod
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=80m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/k8s-testimages/kubekins-e2e:v20181105-66d3bcb98-master
