periodics:
- decorate: true
  decoration_config:
    timeout: 6000000000000 # 100 minutes
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-default-parallel
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=80m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master

- decorate: true
  decoration_config:
    timeout: 37200000000000 # 620 minutes
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-default-serial
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-f
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Slow\]|\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=800m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master

- decorate: true
  decoration_config:
    timeout: 6000000000000 # 100 minutes
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-stable1-parallel
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke-latest-1.11
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=80m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master

- decorate: true
  decoration_config:
    timeout: 37200000000000 # 620 minutes
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-stable1-serial
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke-latest-1.11
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-f
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Slow\]|\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=600m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master

- decorate: true
  decoration_config:
    timeout: 6000000000000 # 100 minutes
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-stable2-parallel
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke-latest-1.12
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=80m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master

- decorate: true
  decoration_config:
    timeout: 37200000000000 # 620 minutes
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: ci-kubernetes-e2e-gke-staging-stable2-serial
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke-latest-1.12
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-f
      - --gke-environment=staging
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Slow\]|\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=600m
      command:
      - runner.sh
      - /workspace/scenarios/kubernetes_e2e.py
      image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master

- decorate: true
  decoration_config:
    timeout: 6000000000000 # 100 minutes
  extra_refs:
  - org: istio
    repo: istio
    base_ref: master
    path_alias: istio.io/istio
  interval: 30m
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  name: periodic-e2e-gke-staging-1-11-istio-addon
  spec:
    containers:
    - args:
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --env=CLOUDSDK_CONTAINER_USE_V1_API=false
      - --env=HUB=docker.io/istio
      - --env=TAG=1.0.3
      - --extract=gke-latest-1.11
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gke-internal-project
      - --gcp-zone=us-central1-f
      - --gke-command-group=beta
      # TODO(senlu): switch to --istio-config=auth=MTLS_PERMISSIVE once that's rolled out
      - --gke-create-command=container clusters create --quiet --num-nodes=4 --no-enable-legacy-authorization --addons=Istio --istio-config=auth=NONE
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=make
      - --test-cmd-args=-C .. e2e_bookinfo_envoyv2_v1alpha3 E2E_ARGS="--skip_setup --namespace=istio-system"
      - --test-cmd-name=istio-addon
      - --timeout=80m
    command:
    - runner.sh
    - /workspace/scenarios/kubernetes_e2e.py
    image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master
