presubmits:
  https://gke-internal-review.googlesource.com/onprem-lab-automation:
  - name: pull-onprem-lab-automation-presubmit
    decorate: true
    always_run: true
    path_alias: gke-internal.googlesource.com/onprem-lab-automation
    spec:
      containers:
      - image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master
        command:
        - make
        args:
        - all
