presubmits:
  https://gke-internal-review.googlesource.com/syllogi/logmon:
  - name: pull-syllogi-logmon-gofmt
    always_run: true
    decorate: true
    path_alias: gke-internal.googlesource.com/syllogi/logmon
    labels:
      prow.k8s.io/gerrit-report-label: "Verified"
    decoration_config:
      gcs_configuration:
        bucket: "syllogi-gob-prow"
        path_strategy: "explicit"
    spec:
      containers:
      - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-1.11
        command:
        - ./hack/verify-gofmt.sh
