periodics:
 - name: ci-runsc-build
   interval: 30m
   agent: kubernetes
   labels:
     preset-service-account: "true"
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20181024-be2f242dd-master
       args:
       - --repo=github.com/google/gvisor=master
       - --repo=team.googlesource.com/gke-kubernetes-tholos/runsc-scripts=master
       - --root=/go/src
       - --upload=gs://gob-prow/logs
       - --scenario=execute
       - --
       - /go/src/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/build.sh

 - name: ci-gvisor-containerd-shim-build
   interval: 1h
   decorate: true
   agent: kubernetes
   labels:
     preset-service-account: "true"
   extra_refs:
   - org: team.googlesource.com/gke-kubernetes-tholos
     repo: gvisor-containerd-shim
     base_ref: master
     path_alias: github.com/google/gvisor-containerd-shim
     clone_uri: https://team.googlesource.com/gke-kubernetes-tholos/gvisor-containerd-shim
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20181024-be2f242dd-master
       command:
       - runner.sh
       args:
       - make
       - push

 - interval: 1h
   agent: kubernetes
   name: ci-containerd-runsc-node-e2e
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20181024-be2f242dd-1.11
       args:
       - --repo=k8s.io/kubernetes=release-1.11
       - --repo=github.com/containerd/cri=master
       - --repo=team.googlesource.com/gke-kubernetes-tholos/runsc-scripts=master
       - --root=/go/src
       - --upload=gs://gob-prow/logs
       - --scenario=kubernetes_e2e
       - --timeout=90
       - --
       - --node-args=--image-config-file=/go/src/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/image-config.yaml
       - --deployment=node
       - --gcp-project=cri-containerd-node-e2e
       - --gcp-zone=us-central1-f
       - '--node-test-args=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
       - --node-tests=true
       - --provider=gce
       - '--test_args=--nodes=8 --focus="\[NodeConformance\]|\[NodeFeature:FSGroup\]|\[NodeFeature:\sImageID\]" --skip="\[Flaky\]|\[Serial\]" --flakeAttempts=2'
       - --timeout=65m

 - interval: 1h
   agent: kubernetes
   name: ci-containerd-runsc-node-e2e-xemu
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20181024-be2f242dd-1.11
       args:
       - --repo=k8s.io/kubernetes=release-1.11
       - --repo=github.com/containerd/cri=master
       - --repo=team.googlesource.com/gke-kubernetes-tholos/runsc-scripts=master
       - --root=/go/src
       - --upload=gs://gob-prow/logs
       - --scenario=kubernetes_e2e
       - --timeout=90
       - --
       - --node-args=--image-config-file=/go/src/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/image-config-xemu.yaml
       - --deployment=node
       - --gcp-project=cri-containerd-node-e2e
       - --gcp-zone=us-central1-f
       - '--node-test-args=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
       - --node-tests=true
       - --provider=gce
       - '--test_args=--nodes=8 --focus="\[NodeConformance\]|\[NodeFeature:FSGroup\]|\[NodeFeature:\sImageID\]" --skip="\[Flaky\]|\[Serial\]" --flakeAttempts=2'
       - --timeout=65m

 - interval: 1h
   agent: kubernetes
   name: ci-containerd-runsc-e2e
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20181024-be2f242dd-1.11
       args:
       - --repo=github.com/containerd/cri=master
       - --repo=team.googlesource.com/gke-kubernetes-tholos/runsc-scripts=master
       - --upload=gs://gob-prow/logs
       - --scenario=kubernetes_e2e
       - --timeout=200
       - --
       - --check-leaked-resources
       - --env=KUBE_MASTER_EXTRA_METADATA=user-data=/workspace/github.com/containerd/cri/test/e2e/master.yaml,containerd-configure-sh=/workspace/github.com/containerd/cri/cluster/gce/configure.sh,containerd-extra-init-sh=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/runsc-e2e-init.sh,containerd-env=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/env
       - --env=KUBE_NODE_EXTRA_METADATA=user-data=/workspace/github.com/containerd/cri/test/e2e/node.yaml,containerd-configure-sh=/workspace/github.com/containerd/cri/cluster/gce/configure.sh,containerd-extra-init-sh=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/runsc-e2e-init.sh,containerd-env=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/env
       - --env=STORAGE_BACKEND=etcd2
       - --env=TEST_ETCD_IMAGE=2.2.1
       - --env=TEST_ETCD_VERSION=2.2.1
       - --env=LOG_DUMP_SYSTEMD_SERVICES=containerd containerd-installation
       - --env=KUBE_CONTAINER_RUNTIME=remote
       - --env=KUBE_CONTAINER_RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock
       - --env=KUBE_CONTAINER_RUNTIME_NAME=containerd
       - --env=KUBE_LOAD_IMAGE_COMMAND=/home/containerd/usr/local/bin/ctr cri load
       - --env=NETWORK_PROVIDER=
       - --env=NON_MASQUERADE_CIDR=0.0.0.0/0
       - --env=KUBELET_TEST_ARGS=--runtime-cgroups=/system.slice/containerd.service
       - --extract=release/stable-1.11
       - --gcp-project=cri-containerd-node-e2e
       - --gcp-node-image=gci
       - --gcp-nodes=4
       - --gcp-zone=us-central1-f
       - --ginkgo-parallel=30
       - --provider=gce
       - --test=false
       - --test-cmd=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/run-e2e.sh
       - --test-cmd-args=--ginkgo.focus=Conformance --ginkgo.skip=\[Serial\]|\[Flaky\] --minStartupPods=8
       - --timeout=180m

 - interval: 1h
   agent: kubernetes
   name: ci-containerd-runsc-e2e-xemu
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20181024-be2f242dd-1.11
       args:
       - --repo=github.com/containerd/cri=master
       - --repo=team.googlesource.com/gke-kubernetes-tholos/runsc-scripts=master
       - --upload=gs://gob-prow/logs
       - --scenario=kubernetes_e2e
       - --timeout=200
       - --
       - --check-leaked-resources
       - --env=KUBE_MASTER_EXTRA_METADATA=user-data=/workspace/github.com/containerd/cri/test/e2e/master.yaml,containerd-configure-sh=/workspace/github.com/containerd/cri/cluster/gce/configure.sh,containerd-extra-init-sh=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/runsc-e2e-init.sh,containerd-env=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/env-xemu
       - --env=KUBE_NODE_EXTRA_METADATA=user-data=/workspace/github.com/containerd/cri/test/e2e/node.yaml,containerd-configure-sh=/workspace/github.com/containerd/cri/cluster/gce/configure.sh,containerd-extra-init-sh=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/runsc-e2e-init.sh,containerd-env=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/env-xemu
       - --env=STORAGE_BACKEND=etcd2
       - --env=TEST_ETCD_IMAGE=2.2.1
       - --env=TEST_ETCD_VERSION=2.2.1
       - --env=LOG_DUMP_SYSTEMD_SERVICES=containerd containerd-installation
       - --env=KUBE_CONTAINER_RUNTIME=remote
       - --env=KUBE_CONTAINER_RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock
       - --env=KUBE_CONTAINER_RUNTIME_NAME=containerd
       - --env=KUBE_LOAD_IMAGE_COMMAND=/home/containerd/usr/local/bin/ctr cri load
       - --env=NETWORK_PROVIDER=
       - --env=NON_MASQUERADE_CIDR=0.0.0.0/0
       - --env=KUBELET_TEST_ARGS=--runtime-cgroups=/system.slice/containerd.service
       - --extract=release/stable-1.11
       - --gcp-project=cri-containerd-node-e2e
       - --gcp-node-image=gci
       - --image-family=cos-xemu
       - --image-project=cri-containerd-node-e2e
       - --gcp-nodes=4
       - --gcp-zone=us-central1-f
       - --ginkgo-parallel=30
       - --provider=gce
       - --test=false
       - --test-cmd=/workspace/team.googlesource.com/gke-kubernetes-tholos/runsc-scripts/run-e2e.sh
       - --test-cmd-args=--ginkgo.focus=Conformance --ginkgo.skip=\[Serial\]|\[Flaky\] --minStartupPods=8
       - --timeout=180m
