presubmits:
  https://team-review.googlesource.com/big-compute-eng/batch:
  - name: pull-batch-presubmit
    always_run: true
    decorate: true
    spec:
      containers:
      - image: gcr.io/kubebatchtest/prowcontainers/prowcontainer:final
        imagePullPolicy: Always
        command:
        - ./prow/RunAcceptanceTests.sh
        resources:
          requests:
            cpu: 4
            memory: "16Gi"

periodics:
 - interval: 1h
   name: ci-bigcomputeeng-batch-acceptance-tests
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/kubebatchtest/prowcontainers/prowcontainer:final
       imagePullPolicy: Always
       args:
       - --clean
       - --repo=team.googlesource.com/big-compute-eng/batch
       - --upload=gs://gob-prow/logs
       - --scenario=execute
       - --
       - /workspace/team.googlesource.com/big-compute-eng/batch/prow/RunAcceptanceTests.sh
       resources:
          requests:
            cpu: 4
            memory: "16Gi"

 - interval: 2h
   name: ci-bigcomputeeng-batch-e2e-gke-autoscaling-tests
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/kubebatchtest/prowcontainers/prowcontainer:final
       imagePullPolicy: Always
       args:
       - --clean
       - --repo=team.googlesource.com/big-compute-eng/batch
       - --upload=gs://gob-prow/logs
       - --scenario=execute
       - --
       - /workspace/team.googlesource.com/big-compute-eng/batch/prow/RunEndToEndTestsOnGke.sh
       resources:
          requests:
            cpu: 6
            memory: "16Gi"

 - interval: 24h
   name: ci-bigcomputeeng-batch-e2e-gce-tests
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - image: gcr.io/kubebatchtest/prowcontainers/prowcontainer:final
       imagePullPolicy: Always
       args:
       - --repo=team.googlesource.com/big-compute-eng/batch
       - --upload=gs://gob-prow/logs
       - --scenario=kubernetes_e2e
       - --timeout=110
       - --
       - --gcp-project=kubebatchtest
       - --gcp-zone=us-central1-f
       - --extract=v1.11.3
       - --provider=gce
       - --test=false
       - --test-cmd=/workspace/team.googlesource.com/big-compute-eng/batch/prow/RunEndToEndTestsOnGce.sh
       - --timeout=90m
       securityContext:
         privileged: true
       resources:
         requests:
           cpu: 6
           memory: "16Gi"
