presubmits:
  https://gke-internal-review.googlesource.com/kubernetes/gke-common-webhooks:
  - name: pull-webhooks-unit
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
        command:
        - "make"
        - "lint"
        - "test"
