# This file contains Kubernetes YAML files for the most important prow
# components. Don't edit resources in this file. Instead, pull them out into
# their own files.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
data:
  plugins.yaml: ""
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: prowjobs.prow.k8s.io
spec:
  group: prow.k8s.io
  version: v1
  names:
    kind: ProwJob
    singular: prowjob
    plural: prowjobs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            max_concurrency:
              type: integer
              minimum: 0
            type:
              type: string
              enum:
              - "presubmit"
              - "postsubmit"
              - "periodic"
              - "batch"
        status:
          properties:
            state:
              type: string
              enum:
              - "triggered"
              - "pending"
              - "success"
              - "failure"
              - "aborted"
              - "error"
          anyOf:
          - not:
              properties:
                state:
                  type: string
                  enum:
                  - "success"
                  - "failure"
                  - "error"
                  - "aborted"
          - required:
            - completionTime
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plank
  labels:
    app: plank
spec:
  replicas: 1 # Do not scale up.
  template:
    metadata:
      labels:
        app: plank
    spec:
      containers:
      - name: plank
        image: gcr.io/k8s-prow/plank:v20180814-0a3efc115
        args:
        - --dry-run=false
        - --github-token-file=
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sinker
  labels:
    app: sinker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sinker
    spec:
      containers:
      - name: sinker
        image: gcr.io/k8s-prow/sinker:v20180814-0a3efc115
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deck
  labels:
    app: deck
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: deck
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: deck
        image: gcr.io/k8s-prow/deck:v20180814-0a3efc115
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
---
apiVersion: v1
kind: Service
metadata:
  name: deck
spec:
  selector:
    app: deck
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: horologium
  labels:
    app: horologium
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: horologium
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: horologium
        image: gcr.io/k8s-prow/horologium:v20180814-0a3efc115
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: deck-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "gob-prow"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: tls-secret
    hosts:
    - prow-gob.gcpnode.com
  rules:
  - host: prow-gob.gcpnode.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: deck
          servicePort: 80
---
# start gerrit
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: gerrit
  name: gerrit-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: gerrit-storage
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: gerrit
  name: gerrit-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gerrit
  labels:
    app: gerrit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gerrit
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: gerrit
        image: gcr.io/gob-prow/gerrit:latest # TODO(senlu): create a stable tag
        imagePullPolicy: Always
        args:
        - ./gerrit
        - --storage=/store/gerrit
        - --gerrit-instance=https://gke-internal-review.googlesource.com
        - --gerrit-projects=test-infra,kubernetes,net/mci,syllogi/cluster-management,kubernetes/gke-common-webhooks,syllogi/logmon
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - mountPath: /store
          name: gerrit-volume
      volumes:
      - name: config
        configMap:
          name: config
      - name: gerrit-volume
        persistentVolumeClaim:
          claimName: gerrit-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: gerrit-team
  name: gerrit-team-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: gerrit-storage
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: gerrit-team
  name: gerrit-team-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gerrit-team
  labels:
    app: gerrit-team
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gerrit-team
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: gerrit-team
        image: gcr.io/gob-prow/gerrit:latest # TODO(senlu): create a stable tag
        imagePullPolicy: Always
        args:
        - ./gerrit
        - --storage=/store/gerrit-team
        - --gerrit-instance=https://team-review.googlesource.com
        - --gerrit-projects=alphabetcloud/galu,gke-kubernetes-enterprise-control/prototype
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - mountPath: /store
          name: gerrit-team-volume
      volumes:
      - name: config
        configMap:
          name: config
      - name: gerrit-team-volume
        persistentVolumeClaim:
          claimName: gerrit-team-storage
