presubmits:
  https://gke-internal-review.googlesource.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver:
  - name: pull-gcp-pd-csi-driver-k8s-integration-latest
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/gcp-compute-persistent-disk-csi-driver
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-1.11
        command:
        - runner.sh
        args:
        - test/run-k8s-integration.sh
        env:
        - name: GCE_PD_BOSKOS_RESOURCE_TYPE
          value: "gke-internal-project"
        securityContext:
          privileged: true
periodics:
 - interval: 2h
   name: periodic-gcp-pd-csi-driver-k8s-integration-latest
   decorate: true
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   extra_refs:
   - org: gke-internal.googlesource.com/kubernetes-sigs
     repo: gcp-compute-persistent-disk-csi-driver
     base_ref: master
     path_alias: sigs.k8s.io/gcp-compute-persistent-disk-csi-driver
     clone_uri: https://gke-internal.googlesource.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver
   spec:
     containers:
     - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-1.11
       command:
       - runner.sh
       args:
       - test/run-k8s-integration.sh
       env:
       - name: GCE_PD_BOSKOS_RESOURCE_TYPE
         value: "gke-internal-project"
       - name: GCE_PD_OVERLAY_NAME
         value: "prow-gke-head"
       - name: GCE_PD_DO_DRIVER_BUILD
         value: "false"
       securityContext:
         privileged: true
 - interval: 4h
   name: periodic-gcp-pd-csi-driver-k8s-integration-staging
   decorate: true
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   extra_refs:
   - org: gke-internal.googlesource.com/kubernetes-sigs
     repo: gcp-compute-persistent-disk-csi-driver
     base_ref: master
     path_alias: sigs.k8s.io/gcp-compute-persistent-disk-csi-driver
     clone_uri: https://gke-internal.googlesource.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver
   spec:
     containers:
     - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-1.11
       command:
       - runner.sh
       args:
       - test/run-k8s-integration.sh
       env:
       - name: GCE_PD_BOSKOS_RESOURCE_TYPE
         value: "gke-internal-project"
       - name: GCE_PD_OVERLAY_NAME
         value: "prow-gke-staging"
       - name: GCE_PD_DO_DRIVER_BUILD
         value: "false"
       securityContext:
         privileged: true
