#############################################################################################################################
# build images of autoscaling components which are then used for tests
#############################################################################################################################

periodics:
- interval: 2h
  name: ci-autoscaling-build-images-latest
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=60
      - --clean
      - --repo=gke-internal.googlesource.com/gke-autoscaling
      - --root=/go/src
      - --timeout=30
      - --scenario=execute
      - --upload=gs://gob-prow/logs
      - -- # stop bootstrap flags
      - ./hack/e2e/build-autoscaling-ci-images-latest
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true

- interval: 2h
  name: ci-autoscaling-build-images-1-11
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=60
      - --clean
      - --repo=gke-internal.googlesource.com/gke-autoscaling
      - --root=/go/src
      - --timeout=30
      - --scenario=execute
      - --upload=gs://gob-prow/logs
      - -- # stop bootstrap flags
      - ./hack/e2e/build-autoscaling-ci-images-1.11
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true

- interval: 2h
  name: ci-autoscaling-build-images-1-12
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=60
      - --clean
      - --repo=gke-internal.googlesource.com/gke-autoscaling
      - --root=/go/src
      - --timeout=30
      - --scenario=execute
      - --upload=gs://gob-prow/logs
      - -- # stop bootstrap flags
      - ./hack/e2e/build-autoscaling-ci-images-1.12
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true



