#############################################################################################################################
# test if CA works in VPC SC secured environment. Uses latest 1.12 version.
#############################################################################################################################

periodics:
- interval: 12h
  name: ci-autoscaling-ca-vpc-sc
  labels:
    preset-k8s-ssh: "true"
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=440
      - --repo=gke-internal.googlesource.com/gke-autoscaling=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=ci-autoscaling-ca-vpc-sc-cluster
      - --deployment=gke
      - --extract=gke-latest-1.12
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --gcp-project=gke-vpc-sc-1
      - --ginkgo-parallel=1
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../test/cluster-autoscaler/e2e/hack/run-e2e.sh
      - --test-cmd-args=--ginkgo.focus=Should be able to scale a node group up from 0|\[Feature:NodeAutoProvisioning\]
      - --timeout=7h

