periodics:
- cron: '0 0 31 2 *' # manual job, set to Feb 31st to never be triggered automatically
  name: ci-kubernetes-e2e-gke-large-performance
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master
      args:
      - --timeout=600
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gke-scale-cluster
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=kubernetes-scale
      - --gcp-zone=us-east1-a
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --quiet --enable-ip-alias --enable-vertical-pod-autoscaling --create-subnetwork name=ip-alias-subnet --cluster-ipv4-cidr=/12 --services-ipv4-cidr=/19
      - --gke-environment=test
      - '--gke-shape={"default":{"Nodes":1999,"MachineType":"n1-standard-1"},"heapster-pool":{"Nodes":1,"MachineType":"n1-standard-8"}}'
      - --provider=gke
      - --test_args=--ginkgo.focus=\sDensity\s\[Feature\:Performance\] # Just density for now
      - --timeout=570m
