####################################################################################################
# test latest k8s with VPA built from HEAD of gke-internal.googlesource.com/gke-autoscaling/master
####################################################################################################

periodics:
- interval: 3h
  name: ci-autoscaling-vpa-full-e2e
  labels:
    preset-k8s-ssh: "true"
    preset-vpa-alpha: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=120
      - --repo=k8s.io/autoscaler=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=vpa-full-latest
      - --deployment=gke
      - --extract=gs://kubernetes-release-gke-internal/ci/latest-autoscaling-full-vpa.txt
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=prow-gob-vpa
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=1
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --enable-vertical-pod-autoscaling
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../vertical-pod-autoscaler/hack/run-e2e-tests.sh
      - --test-cmd-args=full-vpa
      - --timeout=90m

- interval: 4h
  name: ci-autoscaling-vpa-recommender-e2e
  labels:
    preset-k8s-ssh: "true"
    preset-vpa-alpha: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=150
      - --repo=gke-internal.googlesource.com/gke-autoscaling=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=vpa-recommender-latest
      - --deployment=gke
      - --extract=gs://kubernetes-release-gke-internal/ci/latest-autoscaling-vpa-recommender.txt
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=prow-gob-vpa
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=1
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --enable-vertical-pod-autoscaling --enable-stackdriver-kubernetes
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../test/vertical-pod-autoscaler/e2e/hack/run-e2e.sh
      - --test-cmd-args=recommender
      - --timeout=120m

- interval: 3h
  name: ci-autoscaling-vpa-updater-e2e
  labels:
    preset-k8s-ssh: "true"
    preset-vpa-alpha: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=120
      - --repo=k8s.io/autoscaler=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=vpa-updater-latest
      - --deployment=gke
      - --extract=gs://kubernetes-release-gke-internal/ci/latest-autoscaling-vpa-updater.txt
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=prow-gob-vpa
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=1
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --enable-vertical-pod-autoscaling
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../vertical-pod-autoscaler/hack/run-e2e-tests.sh
      - --test-cmd-args=updater
      - --timeout=90m

- interval: 3h
  name: ci-autoscaling-vpa-admission-controller-e2e
  labels:
    preset-k8s-ssh: "true"
    preset-vpa-alpha: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=120
      - --repo=k8s.io/autoscaler=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=vpa-admission-controller-latest
      - --deployment=gke
      - --extract=gs://kubernetes-release-gke-internal/ci/latest-autoscaling-vpa-admission-controller.txt
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=prow-gob-vpa
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=1
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --enable-vertical-pod-autoscaling
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../vertical-pod-autoscaler/hack/run-e2e-tests.sh
      - --test-cmd-args=admission-controller
      - --timeout=90m

- interval: 4h
  name: ci-autoscaling-vpa-actuation-e2e
  labels:
    preset-k8s-ssh: "true"
    preset-vpa-alpha: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=150
      - --repo=gke-internal.googlesource.com/gke-autoscaling=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=vpa-actuation-latest
      - --deployment=gke
      - --extract=gs://kubernetes-release-gke-internal/ci/latest-autoscaling-vpa-actuation.txt
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=prow-gob-vpa
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=1
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --enable-vertical-pod-autoscaling
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../test/vertical-pod-autoscaler/e2e/hack/run-e2e.sh
      - --test-cmd-args=actuation
      - --timeout=120m

- interval: 4h
  name: ci-autoscaling-vpa-actuation-ca-e2e
  labels:
    preset-k8s-ssh: "true"
    preset-vpa-alpha: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=150
      - --repo=gke-internal.googlesource.com/gke-autoscaling=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=vpa-actuation-ca-latest
      - --deployment=gke
      - --extract=gs://kubernetes-release-gke-internal/ci/latest-autoscaling-vpa-actuation.txt
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=prow-gob-vpa
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=1
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --enable-vertical-pod-autoscaling --enable-autoscaling --num-nodes=6 --min-nodes=6 --max-nodes=30
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../test/vertical-pod-autoscaler/e2e/hack/run-e2e.sh
      - --test-cmd-args=actuation-ca
      - --timeout=120m

- interval: 4h
  name: ci-autoscaling-vpa-actuation-nap-e2e
  labels:
    preset-k8s-ssh: "true"
    preset-vpa-alpha: "true"
  spec:
    containers:
    - image: gcr.io/gke-test-infra/kubekins-e2e:v20181221-f9eff05-master
      args:
      - --timeout=150
      - --repo=gke-internal.googlesource.com/gke-autoscaling=master
      - --root=/go/src
      - --upload=gs://gob-prow/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=vpa-actuation-nap-latest
      - --deployment=gke
      - --extract=gs://kubernetes-release-gke-internal/ci/latest-autoscaling-vpa-actuation.txt
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=prow-gob-vpa
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=1
      - --gke-command-group=beta
      - --gke-create-command=container clusters create --enable-vertical-pod-autoscaling --enable-autoscaling --enable-autoprovisioning --num-nodes=6 --min-nodes=6 --max-nodes=30 --max-cpu=40 --max-memory=400
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../test/vertical-pod-autoscaler/e2e/hack/run-e2e.sh
      - --test-cmd-args=actuation-nap
      - --timeout=120m
