presubmits:
  # TODO(senlu): Consider a rewrite of this into the modern prow format.
  https://team-review.googlesource.com/gke-kubernetes-enterprise-control/prototype:
  - name: nomos-presubmit
    always_run: true
    decorate: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
        command:
        - runner.sh
        args:
        - make
        - test
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true

periodics:
 # Continuous integration runs all nomos tests based off of contents of the
 # "master" branch, reinstalling the contents of the cluster in the process.
 - interval: 19m
   name: nomos-ci
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   decorate: true
   decoration_config:
     timeout: 3600000000000 # 60 minutes
   extra_refs:
   - org: team.googlesource.com/gke-kubernetes-enterprise-control
     repo: prototype
     base_ref: master
     clone_uri: https://team.googlesource.com/gke-kubernetes-enterprise-control/prototype
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
       command:
       - runner.sh
       args:
       - make
       - ci-test-e2e
       env:
       # The ambient UNIX user name as would be defined inside a shell.
       - name: USER
         value: "nomos-ci"
       # The ambient UNIX numeric user id as would be defined inside a shell.
       - name: UID
         value: "10333"
       # The ambient UNIX numeric group id as would be defined inside a shell.
       - name: GID
         value: "10333"
       # TODO(bentheelder): remove bandaid once we have this metadata exposed
       # properly, first-class
       - name: METADATA_BANDAID
         value: "true"
       # docker-in-docker needs privileged mode
       securityContext:
         privileged: true
       volumeMounts:
       - name: prober-cred
         mountPath: /etc/prober-gcp-service-account
         readOnly: true
     volumes:
     - name: prober-cred
       secret:
         secretName: nomos-prober-runner-gcp-client-key

# Runs a release process that builds go/nomos releases based off of latest HEAD
# that passes the build.
 - interval: 24h
   name: nomos-release
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   spec:
     activeDeadlineSeconds: 7200  # 2 hours
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
       args:
       - --clean
       - --timeout=300
       - --repo=team.googlesource.com/gke-kubernetes-enterprise-control/prototype=master
       - --scenario=execute
       - --upload=gs://gob-prow/logs
       - --
       - make
       - --
       - --makefile=Makefile.release
       - autorelease
       env:
       # The ambient UNIX user name as would be defined inside a shell.
       - name: USER
         value: "nomos-release"
       # The ambient UNIX numeric user id as would be defined inside a shell.
       - name: UID
         value: "10333"
       # The ambient UNIX numeric group id as would be defined inside a shell.
       - name: GID
         value: "10333"
       # docker-in-docker needs privileged mode
       securityContext:
         privileged: true
       volumeMounts:
       - name: prober-cred
         mountPath: /etc/prober-gcp-service-account
         readOnly: true
     volumes:
     - name: prober-cred
       secret:
         secretName: nomos-prober-runner-gcp-client-key

# Runs a release process that builds go/nomos releases based off of latest HEAD
# that passes the build.
 - interval: 24h
   name: nomos-operator-release
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   decorate: true
   decoration_config:
     timeout: 1200000000000 # 20 minutes
   extra_refs:
   - org: team.googlesource.com/gke-kubernetes-enterprise-control
     repo: cluster-operators
     base_ref: master
     clone_uri: https://gke-internal.googlesource.com/cluster-lifecycle/cluster-operators
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
       command:
       - runner.sh
       args:
       - make
       - -C
       - nomos-operator
       - create-release-package
       env:
       # The ambient UNIX user name as would be defined inside a shell.
       - name: USER
         value: "nomos-operator-release"
       # The ambient UNIX numeric user id as would be defined inside a shell.
       - name: UID
         value: "10333"
       # The ambient UNIX numeric group id as would be defined inside a shell.
       - name: GID
         value: "10333"
       # TODO(bentheelder): remove bandaid once we have this metadata exposed
       # properly, first-class
       - name: METADATA_BANDAID
         value: "true"
       # docker-in-docker needs privileged mode
       securityContext:
         privileged: true
       volumeMounts:
       - name: prober-cred
         mountPath: /etc/prober-gcp-service-account
         readOnly: true
       - name: cookies
         mountPath: /etc/cookies
         readOnly: true
     volumes:
     - name: prober-cred
       secret:
         secretName: nomos-prober-runner-gcp-client-key
     - name: cookies
       secret:
         defaultMode: 420
         secretName: http-cookiefile

# Runs a release process that builds go/nomos releases based off of latest HEAD
# that passes the build.
 - interval: 20m
   name: nomos-operator-release-staging
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   decorate: true
   decoration_config:
     timeout: 1200000000000 # 20 minutes
   extra_refs:
   - org: team.googlesource.com/gke-kubernetes-enterprise-control
     repo: cluster-operators
     base_ref: master
     clone_uri: https://gke-internal.googlesource.com/cluster-lifecycle/cluster-operators
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
       command:
       - runner.sh
       args:
       - make
       - -C
       - nomos-operator
       - create-release-package
       env:
       # The ambient UNIX user name as would be defined inside a shell.
       - name: USER
         value: "nomos-operator-release-staging"
       # The ambient UNIX numeric user id as would be defined inside a shell.
       - name: UID
         value: "10333"
       # The ambient UNIX numeric group id as would be defined inside a shell.
       - name: GID
         value: "10333"
       # TODO(bentheelder): remove bandaid once we have this metadata exposed
       # properly, first-class
       - name: METADATA_BANDAID
         value: "true"
       # docker-in-docker needs privileged mode
       securityContext:
         privileged: true
       volumeMounts:
       - name: prober-cred
         mountPath: /etc/prober-gcp-service-account
         readOnly: true
       - name: cookies
         mountPath: /etc/cookies
         readOnly: true
     volumes:
     - name: prober-cred
       secret:
         secretName: nomos-prober-runner-gcp-client-key
     - name: cookies
       secret:
         defaultMode: 420
         secretName: http-cookiefile


# Canary version of release job on podutil (can be triggered manually)
 - interval: 24h
   name: nomos-release-canary
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   decorate: true
   decoration_config:
     timeout: 3600000000000 # 60 minutes
   extra_refs:
   - org: team.googlesource.com/gke-kubernetes-enterprise-control
     repo: prototype
     base_ref: master
     clone_uri: https://team.googlesource.com/gke-kubernetes-enterprise-control/prototype
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
       command:
       - runner.sh
       args:
       - make
       - --makefile=Makefile.release
       - autorelease-local
       env:
       # The ambient UNIX user name as would be defined inside a shell.
       - name: USER
         value: "nomos-release"
       # The ambient UNIX numeric user id as would be defined inside a shell.
       - name: UID
         value: "10333"
       # The ambient UNIX numeric group id as would be defined inside a shell.
       - name: GID
         value: "10333"
       # TODO(bentheelder): remove bandaid once we have this metadata exposed
       # properly, first-class
       - name: METADATA_BANDAID
         value: "true"
       # docker-in-docker needs privileged mode
       securityContext:
         privileged: true
       volumeMounts:
       - name: prober-cred
         mountPath: /etc/prober-gcp-service-account
         readOnly: true
     volumes:
     - name: prober-cred
       secret:
         secretName: nomos-prober-runner-gcp-client-key

# Tests go/nomos against GKE 1.11.x.
# See "nomos-ci" job above for all relevant comments.  The jobs should be by
# and large the same.
 - interval: 23m
   name: nomos-ci-gke-111
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   decorate: true
   decoration_config:
     timeout: 3600000000000 # 60 minutes
   extra_refs:
   - org: team.googlesource.com/gke-kubernetes-enterprise-control
     repo: prototype
     base_ref: master
     clone_uri: https://team.googlesource.com/gke-kubernetes-enterprise-control/prototype
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
       command:
       - runner.sh
       args:
       - make
       - ci-test-e2e
       env:
       # The ambient UNIX user name as would be defined inside a shell.
       - name: USER
         value: "nomos-ci-gke-111"
       # The ambient UNIX numeric user id as would be defined inside a shell.
       - name: UID
         value: "10333"
       # The ambient UNIX numeric group id as would be defined inside a shell.
       - name: GID
         value: "10333"
       # TODO(bentheelder): remove bandaid once we have this metadata exposed
       # properly, first-class
       - name: METADATA_BANDAID
         value: "true"
       # docker-in-docker needs privileged mode
       securityContext:
         privileged: true
       volumeMounts:
       - name: prober-cred
         mountPath: /etc/prober-gcp-service-account
         readOnly: true
     volumes:
     - name: prober-cred
       secret:
         secretName: nomos-prober-runner-gcp-client-key

# Tests go/nomos against an alpha GKE 1.11.x cluster.
# See "nomos-ci" job above for all relevant comments.  The jobs should be by
# and large the same.
 - interval: 23m
   name: nomos-ci-gke-111-a
   labels:
     preset-service-account: "true"
     preset-dind-enabled: "true"
   decorate: true
   decoration_config:
     timeout: 3600000000000 # 60 minutes
   extra_refs:
   - org: team.googlesource.com/gke-kubernetes-enterprise-control
     repo: prototype
     base_ref: master
     clone_uri: https://team.googlesource.com/gke-kubernetes-enterprise-control/prototype
   spec:
     containers:
     - image: gcr.io/k8s-testimages/kubekins-e2e:v20190117-9a712c1e6-master
       command:
       - runner.sh
       args:
       - make
       - ci-test-e2e
       env:
       - name: USER
         value: "nomos-ci-gke-111-a"
       - name: UID
         value: "10333"
       - name: GID
         value: "10333"
       # TODO(bentheelder): remove bandaid once we have this metadata exposed
       # properly, first-class
       - name: METADATA_BANDAID
         value: "true"
       securityContext:
         privileged: true
       volumeMounts:
       - name: prober-cred
         mountPath: /etc/prober-gcp-service-account
         readOnly: true
     volumes:
     - name: prober-cred
       secret:
         secretName: nomos-prober-runner-gcp-client-key
