presubmits:
  https://gke-internal-review.googlesource.com/cluster-lifecycle/cluster-operators:
  - name: pull-cluster-lifecycle-cluster-operators-unittest
    always_run: true
    decorate: true
    path_alias: gke-internal.googlesource.com/cluster-lifecycle/cluster-operators
    spec:
      containers:
      - image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master
        command:
        - ./scripts/ci-test.sh
  - name: pull-cluster-lifecycle-cluster-operators-smoketest
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    path_alias: gke-internal.googlesource.com/cluster-lifecycle/cluster-operators
    spec:
      containers:
      - image: gcr.io/gke-test-infra/kubekins-e2e:v20181127-ae09170-master
        command:
        - runner.sh
        args:
        - ./scripts/ci-e2e.sh
