# Start of StatefulSet
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: boskos
  namespace: test-pods
spec:
  serviceName: "boskos"
  replicas: 1  # one canonical source of resources
  template:
    metadata:
      labels:
        app: boskos
      namespace: test-pods
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos
        image: gcr.io/k8s-testimages/boskos:v20180405-12e892d69
        args:
        - --config=/etc/config/config
        - --namespace=test-pods
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: boskos-config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: boskos-config
        configMap:
          name: resources
---
apiVersion: v1
kind: Service
metadata:
  name: boskos
  namespace: test-pods
spec:
  selector:
    app: boskos
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 8080