periodics:
 - interval: 30m
   agent: kubernetes
   name: ci-kubernetes-e2e-gke-spanetcd
   labels:
     preset-service-account: "true"
     preset-k8s-ssh: "true"
   spec:
     containers:
     - args:
       - --timeout=70
       - --bare
       - --scenario=kubernetes_e2e
       - --upload=gs://gob-prow/logs
       - --
       - --check-leaked-resources
       - --cluster=gke-spanetcd
       - --deployment=gke
       - --extract=gke-latest
       - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
       - --gcp-node-image=gci
       - --gcp-project=wojtekt-gke-dev
       - --gcp-zone=us-central1-c
       - --ginkgo-parallel=30
       - --gke-environment=https://wojtekt-gke-sandbox-test-container.sandbox.googleapis.com/
       - --gke-create-command=container clusters create --quiet --cluster-version=1.13.0-alpha.0.2097+72db8265bd36f3-dirty-wojtekt --num-nodes=4
       - --provider=gke
       - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
       - --timeout=50m
       image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master