presubmits:
  https://team-review.googlesource.com/alphabetcloud/galu:
  - name: pull-galu-presubmit
    always_run: true
    decorate: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180918-b58d77e83-master
        command:
        - runner.sh
        args:
        - ./prow/presubmit.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
